/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-08-02 11:30:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import sethi.vishal.MyWebApp.entity.User;
import java.util.Iterator;
import sethi.vishal.MyWebApp.entity.Product;
import java.util.List;
import sethi.vishal.MyWebApp.entity.*;
import java.util.List;
import sethi.vishal.MyWebApp.classes.*;

public final class profilepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Navigation.jsp", Long.valueOf(1500571715886L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.entity");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.classes");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.User");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>MobiWorld</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("      <div class=\"page-loader\">\r\n");
      out.write("        <div class=\"loader\">Loading...</div>\r\n");
      out.write("      </div>\r\n");
      out.write("       \r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>MobiWorld</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <style rel=\"stylesheet\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t#searchInput{\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t    float:right; \r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t     \r\n");
      out.write("    \t}\r\n");
      out.write("    \t.Mydropbtn {\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    color: white;\r\n");
      out.write("\t\t    padding: 8px;\r\n");
      out.write("\t\t    font-size: 16px;\r\n");
      out.write("\t\t    border-radius: 10px;\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t    margin-bottom: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    min-width: 300px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    margin-top:62px;\r\n");
      out.write("    margin-left:5px;\r\n");
      out.write("     \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content a:hover {background-color: #f1f1f1}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown:hover .Mydropdown-content {\r\n");
      out.write("\tmargin-left:5px;\r\n");
      out.write("     \r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown:hover .Mydropbtn {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\tfunction openDropDown(){\r\n");
      out.write("\t\tvar drop = document.getElementById('dropMeDown');\r\n");
      out.write("\t\tvar content = document.getElementById('searchBox');\r\n");
      out.write("\t\tcontent.style.display = 'block';\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction closeDropDown(){\r\n");
      out.write("\t\tvar drop =  document.getElementById('dropMeDown');\r\n");
      out.write("\t\tvar content = document.getElementById('searchBox');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tcontent.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("       \r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\" id=\"navBar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"Index\">MobiWorld</a>\r\n");
      out.write("          \t <div  class=\"Mydropdown\" onfocus=\"openDropDown()\" onblur=\"closeDropDown()\" id = \"dropMeDown\">\r\n");
      out.write("          \t <input class=\"Mydropbtn\" id=\"searchBox\"  onfocus=\"openDropDown()\" value=\"charger\"   oninput=\"fetchResults();openDropDown();\" style=\"float:right;margin-top: 5%;color:black\" class=\"navbar-header\" type=\"text\" placeholder=\"Press Enter to search\">\r\n");
      out.write("          \t <div id=\"searchDropDown\" class=\"Mydropdown-content\">\r\n");
      out.write("          \t \t  \r\n");
      out.write("          \t \t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("          \t </div>\r\n");
      out.write("          \t \r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("          \t\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li  class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"ShowProducts?type=1&sort=default&page=1\"     data-toggle=\"dropdown\">Chargers</a>\r\n");
      out.write(" \t\t\t\t\t<!-- Here Number of Dropdowns are removed -->\t\t\t\t\t\t\t\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a target=\"_blank\" class=\"dropdown-toggle\" href=\"ShowProducts?type=2&sort=default&page=1\" data-toggle=\"dropdown\">Earphones</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"ShowProducts?type=3&sort=default&page=1\" data-toggle=\"dropdown\">Datacable</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"ShowProducts?type=4&sort=default&page=1\" data-toggle=\"dropdown\">ScreenGaurd</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"> <a class=\"dropdown-toggle\" href=\"Contact\" data-toggle=\"dropdown\">Contact Us</a> \r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("               \r\n");
      out.write("              <!--li.dropdoswn.navbar-cart-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\r\n");
      out.write("              <!--        span.icon-basket-->\r\n");
      out.write("              <!--        |-->\r\n");
      out.write("              <!--        span.cart-item-number 2-->\r\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                .cart-sub-totle-->\r\n");
      out.write("              <!--                    strong Total: $476.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\r\n");
      out.write("              <!--li.dropdown-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\r\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .dropdown-search-->\r\n");
      out.write("              <!--                form(role='form')-->\r\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\r\n");
      out.write("              <!--                        i.fa.fa-search-->\r\n");
      out.write("              ");

              	List<String> titles = new ArrayList<String>();
              	List<String> hrefs = new ArrayList<String>();
              	String log;
              	if(session.getAttribute("user")!=null){
              		User user = (User)session.getAttribute("user");
              		titles.add(0, "   View Profile");
              		titles.add(1, "   Orders");
              		titles.add(2, "   Cart");
              		titles.add(3, "   SignOut");
              		
              		hrefs.add(0,"Profile");
              		hrefs.add(1, "Orders");
              		hrefs.add(2,"DisplayCart");
              		hrefs.add(3,"Signout");
              		
              		log = "Hello, "+user.getEmail();
					
              	}else{
              		titles.add(0, "SignIn");
              		titles.add(1, "Register");
              		hrefs.add(0, "#");
              		hrefs.add(1, "#");
              		
              		log = "Hello, "+"Sign in";
              	}
              
              	int len = titles.size();
              
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">");
      out.print(log );
      out.write("</a>\r\n");
      out.write("                   <ul class=\"dropdown-menu\">\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                  ");
 for(int i=0;i<len;i++){ 
      out.write("\r\n");
      out.write("                  ");
 if(len==2) { 
      out.write("\r\n");
      out.write("                  \t\t<li><a href=\"");
      out.print( hrefs.get(i));
      out.write("\" onclick=\"openLogin();return false;\">");
      out.print(titles.get(i) );
      out.write("</a></li>\r\n");
      out.write("                  ");
}  
      out.write("\r\n");
      out.write("\t\t\t        ");
if(len==4) {
      out.write("\r\n");
      out.write("\t\t            <li><a href=\"");
      out.print( hrefs.get(i));
      out.write('"');
      out.write('>');
      out.print(titles.get(i) );
      out.write("</a></li>\r\n");
      out.write("\t                ");
 } 
      out.write("\r\n");
      out.write("                  ");
} 
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/basic.js\"></script>\r\n");
      out.write("      </nav>");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("      <div class=\"main\">\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"module\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-8 col-sm-offset-2\">\r\n");
      out.write("                <h4 class=\"font-alt mb-0\">Profile</h4>\r\n");
      out.write("                <hr class=\"divider-w mt-10 mb-20\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div role=\"tabpanel\">\r\n");
      out.write("                  <ul class=\"nav nav-tabs font-alt\" role=\"tablist\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"#personalinfo\" data-toggle=\"tab\">Personal Info</a></li>\r\n");
      out.write("                    <li><a href=\"#address\" data-toggle=\"tab\">Address</a></li>\r\n");
      out.write("                    <li><a href=\"#changepassword\" data-toggle=\"tab\">Add/Change Password</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("                  ");
 User userForProfile = (User)session.getAttribute("user"); 
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("                  <div class=\"tab-content\">\r\n");
      out.write("                    <div class=\"tab-pane active\" id=\"personalinfo\"> \r\n");
      out.write("                    \t<img alt=\"\" src=\"");
      out.print( userForProfile.getImageurl());
      out.write("\">\r\n");
      out.write("                    \t<br><br>\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t<font size=\"4\">Name: </font><font size=\"5\">");
      out.print( userForProfile.getEmail() );
      out.write(" </font><br><br>\r\n");
      out.write("                    \t<font size=\"4\">Email: </font><font size=\"5\"> ");
      out.print(userForProfile.getName() );
      out.write(" </font><br><br>\r\n");
      out.write("                    \t<font size=\"4\">Gender: </font><font size=\"5\"> Male </font><br><br>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    \r\n");
      out.write("                    ");

                    	boolean[] selinfo = (boolean[])session.getAttribute("selinfo");
                    	String text = "", hrefText="",href="" ;
                    	if(selinfo[0]==true&&selinfo[1]==true){
                    		text = "for Seller Panel Please";
                    		href = "SellerPanel";
                    		hrefText = "Click Here";
                    	}else if(selinfo[0]&&!selinfo[1]){
                    		text = "Wait For Application Acceptance";
                    		href = "";
                    		hrefText = "";
                    	}else if(!selinfo[0]){
                    		text = "to become seller, ";
                    		hrefText = "Register Here";
                    		href = "SellerWant";
                    				
                    	}
                    
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \t\r\n");
      out.write("                    <h3 style=\"color: red;\">");
      out.print( text );
      out.write(" <a href = \"");
      out.print( href);
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(hrefText );
      out.write("</a></h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-pane\" id=\"address\"> \r\n");
      out.write("                    \t\t\r\n");
      out.write("\t\t\t\t                    \t\t\r\n");
      out.write("\t\t\t\t                    \t\t<hr class=\"divider-w pt-20\">\r\n");
      out.write("\t\t\t\t            <div class=\"row\">\r\n");
      out.write("\t\t\t\t              <div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t                <table class=\"table table-striped table-border checkout-table\">\r\n");
      out.write("\t\t\t\t                  <tbody>\r\n");
      out.write("\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t                      <th class=\"hidden-xs\">Sno.</th>\r\n");
      out.write("\t\t\t\t                      <th>Address</th>\r\n");
      out.write("\t\t\t\t                      <th class=\"hidden-xs\">Remove</th>\r\n");
      out.write("\t\t\t\t                       \r\n");
      out.write("\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                   ");
 List<Address> list = (List<Address>)session.getAttribute("address");
				                   		for(int i=0,j=list.size();i<j;i++){
					                   	Address add = list.get(i);
				                   
      out.write("  \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                     \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t                      <td class=\"hidden-xs\">");
      out.print( i+1 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t                      <td>\r\n");
      out.write("\t\t\t\t                        <h5 class=\"product-title font-alt\">");
      out.print(add.getAddress() );
      out.write(" </h5>\r\n");
      out.write("\t\t\t\t                      </td>\r\n");
      out.write("\t\t\t\t                       \r\n");
      out.write("\t\t\t\t                       \r\n");
      out.write("\t\t\t\t                      <td class=\"pr-remove\"><a href=\"RemoveAddress?id=");
      out.print(add.getId());
      out.write(" \" title=\"Remove\"><i class=\"fa fa-times\"></i></a></td>\r\n");
      out.write("\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t             \r\n");
      out.write("\t\t\t\t                   ");
 }
      out.write(" \r\n");
      out.write("\t\t\t\t                   \r\n");
      out.write("\t\t\t\t                  \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                    \r\n");
      out.write("\t\t\t\t                  </tbody>\r\n");
      out.write("\t\t\t\t                </table>\r\n");
      out.write("\t\t\t\t              </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            \r\n");
      out.write("\t <h4 >Add New Address</h4>\r\n");
      out.write("                <form class=\"form\" role=\"form\" action=\"InsertAddress\" method = \"post\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control input-lg\" required=\"required\" type=\"text\" name = \"name\" placeholder=\"Full Name\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"number\" maxlength=\"10\"  required=\"required\" name = \"phone\" placeholder=\"Ten Digit Phone Number\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control input-sm\" required=\"required\" type=\"number\" name=\"pincode\" placeholder=\"6 digit pincode\"/>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" required=\"required\" name=\"address\" placeholder=\"Full Address Including Street name\"  />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" required=\"required\" name=\"landmark\" placeholder=\"Landmark\"  />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" required=\"required\" name=\"city\" placeholder=\"City\"  />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <input class=\"form-control\" type=\"text\" required=\"required\" name=\"state\" placeholder=\"State\"  />\r\n");
      out.write("                  </div>\r\n");
      out.write("                   <br>\r\n");
      out.write("                  <button class=\"btn btn-d btn-round\" type=\"submit\">Add Address</button>&nbsp;\r\n");
      out.write("                </form>\r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t                    \t\t\r\n");
      out.write("                    \t\r\n");
      out.write("    </div>\t\t              \r\n");
      out.write("                    <div class=\"tab-pane active\" id=\"changepassword\"> \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                 \r\n");
      out.write("                 \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"module-small bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">About Titan</h5>\r\n");
      out.write("                  <p>The languages only differ in their grammar, their pronunciation and their most common words.</p>\r\n");
      out.write("                  <p>Phone: +1 234 567 89 10</p>Fax: +1 234 567 89 10\r\n");
      out.write("                  <p>Email:<a href=\"#\">somecompany@example.com</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Recent Comments</h5>\r\n");
      out.write("                  <ul class=\"icon-list\">\r\n");
      out.write("                    <li>Maria on <a href=\"#\">Designer Desk Essentials</a></li>\r\n");
      out.write("                    <li>John on <a href=\"#\">Realistic Business Card Mockup</a></li>\r\n");
      out.write("                    <li>Andy on <a href=\"#\">Eco bag Mockup</a></li>\r\n");
      out.write("                    <li>Jack on <a href=\"#\">Bottle Mockup</a></li>\r\n");
      out.write("                    <li>Mark on <a href=\"#\">Our trip to the Alps</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Blog Categories</h5>\r\n");
      out.write("                  <ul class=\"icon-list\">\r\n");
      out.write("                    <li><a href=\"#\">Photography - 7</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Web Design - 3</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Illustration - 12</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Marketing - 1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Wordpress - 16</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Popular Posts</h5>\r\n");
      out.write("                  <ul class=\"widget-posts\">\r\n");
      out.write("                    <li class=\"clearfix\">\r\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-1.jpg\" alt=\"Post Thumbnail\"/></a></div>\r\n");
      out.write("                      <div class=\"widget-posts-body\">\r\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Designer Desk Essentials</a></div>\r\n");
      out.write("                        <div class=\"widget-posts-meta\">23 january</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"clearfix\">\r\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-2.jpg\" alt=\"Post Thumbnail\"/></a></div>\r\n");
      out.write("                      <div class=\"widget-posts-body\">\r\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Realistic Business Card Mockup</a></div>\r\n");
      out.write("                        <div class=\"widget-posts-meta\">15 February</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"divider-d\">\r\n");
      out.write("        <footer class=\"footer bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2017&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!--  \r\n");
      out.write("    JavaScripts\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
