/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-05-26 04:37:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js\" async defer>\n");
      out.write("    function onSignIn(googleUser) {\n");
      out.write("    \t  var profile = googleUser.getBasicProfile();\n");
      out.write("    \t  console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.\n");
      out.write("    \t  console.log('Name: ' + profile.getName());\n");
      out.write("    \t  console.log('Image URL: ' + profile.getImageUrl());\n");
      out.write("    \t  console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.\n");
      out.write("    \t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    <meta name=\"google-signin-client_id\" content=\"372475238802-l5mefq2g0mub1gmsna523i38o52c2900.apps.googleusercontent.com\">\n");
      out.write("    <!--  \n");
      out.write("    Document Title\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <title>Titan | Multipurpose HTML5 Template</title>\n");
      out.write("    <!--  \n");
      out.write("    Favicons\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("    <!--  \n");
      out.write("    Stylesheets\n");
      out.write("    =============================================\n");
      out.write("    \n");
      out.write("    -->\n");
      out.write("    <!-- Default stylesheets-->\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Template specific stylesheets-->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Main stylesheet and color file-->\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\n");
      out.write("   \n");
      out.write("    <main>\n");
      out.write("     \n");
      out.write("      <div class=\"page-loader\">\n");
      out.write("        <div class=\"loader\">Loading...</div>\n");
      out.write("      </div>\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"Login.jsp\">Login</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Home</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"index_mp_fullscreen_video_background.html\">Default</a></li>\n");
      out.write("                  <li><a href=\"index_op_fullscreen_gradient_overlay.html\">One Page</a></li>\n");
      out.write("                  <li><a href=\"index_agency.html\">Agency</a></li>\n");
      out.write("                  <li><a href=\"index_portfolio.html\">Portfolio</a></li>\n");
      out.write("                  <li><a href=\"index_restaurant.html\">Restaurant</a></li>\n");
      out.write("                  <li><a href=\"index_finance.html\">Finance</a></li>\n");
      out.write("                  <li><a href=\"index_landing.html\">Landing Page</a></li>\n");
      out.write("                  <li><a href=\"index_photography.html\">Photography</a></li>\n");
      out.write("                  <li><a href=\"index_shop.html\">Shop</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Headers</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Static Image Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_static.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_static.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Flexslider Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_flexslider.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_flexslider.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Video Background Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_video_background.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_video_background.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Text Rotator Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_text_rotator.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_text_rotator.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Gradient Overlay Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_gradient_overlay.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_gradient_overlay.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Pages</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">About</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"about1.html\">About 1</a></li>\n");
      out.write("                      <li><a href=\"about2.html\">About 2</a></li>\n");
      out.write("                      <li><a href=\"about3.html\">About 3</a></li>\n");
      out.write("                      <li><a href=\"about4.html\">About 4</a></li>\n");
      out.write("                      <li><a href=\"about5.html\">About 5</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Services</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"service1.html\">Service 1</a></li>\n");
      out.write("                      <li><a href=\"service2.html\">Service 2</a></li>\n");
      out.write("                      <li><a href=\"service3.html\">Service 3</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Pricing</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"pricing1.html\">Pricing 1</a></li>\n");
      out.write("                      <li><a href=\"pricing2.html\">Pricing 2</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Gallery</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"gallery_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_4.html\">4 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_6.html\">6 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Contact</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"contact1.html\">Contact 1</a></li>\n");
      out.write("                      <li><a href=\"contact2.html\">Contact 2</a></li>\n");
      out.write("                      <li><a href=\"contact3.html\">Contact 3</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Restaurant menu</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"restaurant_menu1.html\">Menu 2 Columns</a></li>\n");
      out.write("                      <li><a href=\"restaurant_menu2.html\">Menu 3 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"login_register.html\">Login / Register</a></li>\n");
      out.write("                  <li><a href=\"faq.html\">FAQ</a></li>\n");
      out.write("                  <li><a href=\"404.html\">Page 404</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Portfolio</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed - Gutter</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width - Gutter</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Masonry</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_2.html\">2 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_3.html\">3 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_4.html\">4 Columns</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_2.html\">2 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_3.html\">3 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_4.html\">4 Columns</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Hover Style</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_hover_black.html\">Black</a></li>\n");
      out.write("                      <li><a href=\"portfolio_hover_gradient.html\">Gradient</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Single</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Image</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_image1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_image2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Slider</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_slider1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_slider2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Video</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_video1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_video2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Blog</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Standard</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_standard_left_sidebar.html\">Left Sidebar</a></li>\n");
      out.write("                      <li><a href=\"blog_standard_right_sidebar.html\">Right Sidebar</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Grid</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_grid_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Masonry</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Single</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_single_left_sidebar.html\">Left Sidebar</a></li>\n");
      out.write("                      <li><a href=\"blog_single_right_sidebar.html\">Right Sidebar</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Features</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li><a href=\"alerts-and-wells.html\"><i class=\"fa fa-bolt\"></i> Alerts and Wells</a></li>\n");
      out.write("                  <li><a href=\"buttons.html\"><i class=\"fa fa-link fa-sm\"></i> Buttons</a></li>\n");
      out.write("                  <li><a href=\"tabs_and_accordions.html\"><i class=\"fa fa-tasks\"></i> Tabs &amp; Accordions</a></li>\n");
      out.write("                  <li><a href=\"content_box.html\"><i class=\"fa fa-list-alt\"></i> Contents Box</a></li>\n");
      out.write("                  <li><a href=\"forms.html\"><i class=\"fa fa-check-square-o\"></i> Forms</a></li>\n");
      out.write("                  <li><a href=\"icons.html\"><i class=\"fa fa-star\"></i> Icons</a></li>\n");
      out.write("                  <li><a href=\"progress-bars.html\"><i class=\"fa fa-server\"></i> Progress Bars</a></li>\n");
      out.write("                  <li><a href=\"typography.html\"><i class=\"fa fa-font\"></i> Typography</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Shop</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Product</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"shop_product_col_3.html\">3 columns</a></li>\n");
      out.write("                      <li><a href=\"shop_product_col_4.html\">4 columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"shop_single_product.html\">Single Product</a></li>\n");
      out.write("                  <li><a href=\"shop_checkout.html\">Checkout</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!--li.dropdown.navbar-cart-->\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\n");
      out.write("              <!--        span.icon-basket-->\n");
      out.write("              <!--        |-->\n");
      out.write("              <!--        span.cart-item-number 2-->\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\n");
      out.write("              <!--                .navbar-cart-img-->\n");
      out.write("              <!--                    a(href='#')-->\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\n");
      out.write("              <!--                .navbar-cart-title-->\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\n");
      out.write("              <!--                    br-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\n");
      out.write("              <!--                .navbar-cart-img-->\n");
      out.write("              <!--                    a(href='#')-->\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\n");
      out.write("              <!--                .navbar-cart-title-->\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\n");
      out.write("              <!--                    br-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .clearfix-->\n");
      out.write("              <!--                .cart-sub-totle-->\n");
      out.write("              <!--                    strong Total: $476.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .clearfix-->\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\n");
      out.write("              <!--li.dropdown-->\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .dropdown-search-->\n");
      out.write("              <!--                form(role='form')-->\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\n");
      out.write("              <!--                        i.fa.fa-search-->\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"documentation.html\" data-toggle=\"dropdown\">Documentation</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"documentation.html#contact\">Contact Form</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#reservation\">Reservation Form</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#mailchimp\">Mailchimp</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#gmap\">Google Map</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#plugin\">Plugins</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#changelog\">Changelog</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <section class=\"bg-dark-30 showcase-page-header module parallax-bg\" data-background=\"assets/images/MainImage.jpg\">\n");
      out.write("        <div class=\"titan-caption\">\n");
      out.write("          <div class=\"caption-content\">\n");
      out.write("             \n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("      <div class=\"main showcase-page\">\n");
      out.write("        <section class=\"module-extra-small bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-md-8 col-lg-9\">\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"module-medium\" id=\"demos\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row multi-columns-row\">\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_mp_fullscreen_video_background.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/main_demo.jpg\" alt=\"Main Demo\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Main Demo</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_agency.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/agency.jpg\" alt=\"Agency\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Agency</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_portfolio.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/portfolio.jpg\" alt=\"Portfolio\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Portfolio</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_restaurant.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/restaurant.jpg\" alt=\"Restaurant\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Restaurant</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_finance.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/finance.jpg\" alt=\"Finance\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Finance</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_landing.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/landing.jpg\" alt=\"Landing\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Landing</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_photography.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/photography.jpg\" alt=\"Photography\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Photography</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_shop.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/shop.jpg\" alt=\"Shop\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">Shop</h3></a></div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\"><a class=\"content-box\" href=\"index_op_fullscreen_gradient_overlay.html\">\n");
      out.write("                  <div class=\"content-box-image\"><img src=\"assets/images/screenshots/one_page.jpg\" alt=\"One Page\"></div>\n");
      out.write("                  <h3 class=\"content-box-title font-serif\">One Page</h3></a></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <section class=\"module-extra-small bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-md-8 col-lg-9\">\n");
      out.write("                <div class=\"callout-text font-alt\">\n");
      out.write("                  <h4 style=\"margin-top: 0px;\">Start Creating Beautiful Websites</h4>\n");
      out.write("                  <p style=\"margin-bottom: 0px;\">Download Titan Free today!</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-6 col-md-4 col-lg-3\">\n");
      out.write("                <div class=\"callout-btn-box\"><a class=\"btn btn-border-w btn-circle\" href=\"https://themewagon.com/themes/titan/\">Downlaod Free</a></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\n");
      out.write("    </main>\n");
      out.write("    <!--  \n");
      out.write("    JavaScripts\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
