/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-05-29 22:21:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js\" async defer></script>\n");
      out.write("  <meta name=\"google-signin-scope\" content=\"profile email\">\n");
      out.write("  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>\n");
      out.write(" <script src=\"https://apis.google.com/js/platform.js\" async defer></script>\n");
      out.write("\n");
      out.write("  \n");
      out.write(" <meta name=\"google-signin-client_id\" content=\"372475238802-hvh00kjrspaj8eo13au4cqf04rbq815k.apps.googleusercontent.com\">\n");
      out.write(" \n");
      out.write("    <!--  \n");
      out.write("    Document Title\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <title>MobiWorld</title>\n");
      out.write("    <!--  \n");
      out.write("    Favicons\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("    <!--  \n");
      out.write("    Stylesheets\n");
      out.write("    =============================================\n");
      out.write("    \n");
      out.write("    -->\n");
      out.write("    <!-- Default stylesheets-->\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Template specific stylesheets-->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Main stylesheet and color file-->\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\n");
      out.write("    <main>\n");
      out.write("      <div class=\"page-loader\">\n");
      out.write("        <div class=\"loader\">Loading...</div>\n");
      out.write("      </div>\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"index.html\">Titan</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Home</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"index_mp_fullscreen_video_background.html\">Default</a></li>\n");
      out.write("                  <li><a href=\"index_op_fullscreen_gradient_overlay.html\">One Page</a></li>\n");
      out.write("                  <li><a href=\"index_agency.html\">Agency</a></li>\n");
      out.write("                  <li><a href=\"index_portfolio.html\">Portfolio</a></li>\n");
      out.write("                  <li><a href=\"index_restaurant.html\">Restaurant</a></li>\n");
      out.write("                  <li><a href=\"index_finance.html\">Finance</a></li>\n");
      out.write("                  <li><a href=\"index_landing.html\">Landing Page</a></li>\n");
      out.write("                  <li><a href=\"index_photography.html\">Photography</a></li>\n");
      out.write("                  <li><a href=\"index_shop.html\">Shop</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Headers</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Static Image Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_static.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_static.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Flexslider Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_flexslider.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_flexslider.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Video Background Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_video_background.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_video_background.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Text Rotator Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_text_rotator.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_text_rotator.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Gradient Overlay Header</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"index_mp_fullscreen_gradient_overlay.html\">Fulscreen</a></li>\n");
      out.write("                      <li><a href=\"index_mp_classic_gradient_overlay.html\">Classic</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Pages</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">About</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"about1.html\">About 1</a></li>\n");
      out.write("                      <li><a href=\"about2.html\">About 2</a></li>\n");
      out.write("                      <li><a href=\"about3.html\">About 3</a></li>\n");
      out.write("                      <li><a href=\"about4.html\">About 4</a></li>\n");
      out.write("                      <li><a href=\"about5.html\">About 5</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Services</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"service1.html\">Service 1</a></li>\n");
      out.write("                      <li><a href=\"service2.html\">Service 2</a></li>\n");
      out.write("                      <li><a href=\"service3.html\">Service 3</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Pricing</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"pricing1.html\">Pricing 1</a></li>\n");
      out.write("                      <li><a href=\"pricing2.html\">Pricing 2</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Gallery</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"gallery_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_4.html\">4 Columns</a></li>\n");
      out.write("                      <li><a href=\"gallery_col_6.html\">6 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Contact</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"contact1.html\">Contact 1</a></li>\n");
      out.write("                      <li><a href=\"contact2.html\">Contact 2</a></li>\n");
      out.write("                      <li><a href=\"contact3.html\">Contact 3</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Restaurant menu</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"restaurant_menu1.html\">Menu 2 Columns</a></li>\n");
      out.write("                      <li><a href=\"restaurant_menu2.html\">Menu 3 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"login_register.html\">Login / Register</a></li>\n");
      out.write("                  <li><a href=\"faq.html\">FAQ</a></li>\n");
      out.write("                  <li><a href=\"404.html\">Page 404</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Portfolio</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed - Gutter</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_boxed_gutter_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width - Gutter</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"portfolio_full_width_gutter_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Masonry</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Boxed</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_2.html\">2 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_3.html\">3 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_boxed_col_4.html\">4 Columns</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Full Width</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_2.html\">2 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_3.html\">3 Columns</a></li>\n");
      out.write("                          <li><a href=\"portfolio_masonry_full_width_col_4.html\">4 Columns</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Hover Style</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"portfolio_hover_black.html\">Black</a></li>\n");
      out.write("                      <li><a href=\"portfolio_hover_gradient.html\">Gradient</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Single</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Image</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_image1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_image2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Slider</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_slider1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_slider2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Featured Video</a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                          <li><a href=\"portfolio_single_featured_video1.html\">Style 1</a></li>\n");
      out.write("                          <li><a href=\"portfolio_single_featured_video2.html\">Style 2</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Blog</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Standard</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_standard_left_sidebar.html\">Left Sidebar</a></li>\n");
      out.write("                      <li><a href=\"blog_standard_right_sidebar.html\">Right Sidebar</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Grid</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_grid_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Masonry</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_2.html\">2 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_3.html\">3 Columns</a></li>\n");
      out.write("                      <li><a href=\"blog_grid_masonry_col_4.html\">4 Columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Single</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"blog_single_left_sidebar.html\">Left Sidebar</a></li>\n");
      out.write("                      <li><a href=\"blog_single_right_sidebar.html\">Right Sidebar</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Features</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li><a href=\"alerts-and-wells.html\"><i class=\"fa fa-bolt\"></i> Alerts and Wells</a></li>\n");
      out.write("                  <li><a href=\"buttons.html\"><i class=\"fa fa-link fa-sm\"></i> Buttons</a></li>\n");
      out.write("                  <li><a href=\"tabs_and_accordions.html\"><i class=\"fa fa-tasks\"></i> Tabs &amp; Accordions</a></li>\n");
      out.write("                  <li><a href=\"content_box.html\"><i class=\"fa fa-list-alt\"></i> Contents Box</a></li>\n");
      out.write("                  <li><a href=\"forms.html\"><i class=\"fa fa-check-square-o\"></i> Forms</a></li>\n");
      out.write("                  <li><a href=\"icons.html\"><i class=\"fa fa-star\"></i> Icons</a></li>\n");
      out.write("                  <li><a href=\"progress-bars.html\"><i class=\"fa fa-server\"></i> Progress Bars</a></li>\n");
      out.write("                  <li><a href=\"typography.html\"><i class=\"fa fa-font\"></i> Typography</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Shop</a>\n");
      out.write("                <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                  <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Product</a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                      <li><a href=\"shop_product_col_3.html\">3 columns</a></li>\n");
      out.write("                      <li><a href=\"shop_product_col_4.html\">4 columns</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li><a href=\"shop_single_product.html\">Single Product</a></li>\n");
      out.write("                  <li><a href=\"shop_checkout.html\">Checkout</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!--li.dropdown.navbar-cart-->\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\n");
      out.write("              <!--        span.icon-basket-->\n");
      out.write("              <!--        |-->\n");
      out.write("              <!--        span.cart-item-number 2-->\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\n");
      out.write("              <!--                .navbar-cart-img-->\n");
      out.write("              <!--                    a(href='#')-->\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\n");
      out.write("              <!--                .navbar-cart-title-->\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\n");
      out.write("              <!--                    br-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\n");
      out.write("              <!--                .navbar-cart-img-->\n");
      out.write("              <!--                    a(href='#')-->\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\n");
      out.write("              <!--                .navbar-cart-title-->\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\n");
      out.write("              <!--                    br-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .clearfix-->\n");
      out.write("              <!--                .cart-sub-totle-->\n");
      out.write("              <!--                    strong Total: $476.00-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .clearfix-->\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\n");
      out.write("              <!--li.dropdown-->\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\n");
      out.write("              <!--        li-->\n");
      out.write("              <!--            .dropdown-search-->\n");
      out.write("              <!--                form(role='form')-->\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\n");
      out.write("              <!--                    |-->\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\n");
      out.write("              <!--                        i.fa.fa-search-->\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"documentation.html\" data-toggle=\"dropdown\">Documentation</a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"documentation.html#contact\">Contact Form</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#reservation\">Reservation Form</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#mailchimp\">Mailchimp</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#gmap\">Google Map</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#plugin\">Plugins</a></li>\n");
      out.write("                  <li><a href=\"documentation.html#changelog\">Changelog</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <div class=\"main\">\n");
      out.write("        <section class=\"module bg-dark-30\" data-background=\"assets/images/shop/Sony-Xperia-Curve-concept_1.jpg\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\n");
      out.write("               \n");
      out.write("               \n");
      out.write("                 \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        \t\t\n");
      out.write("        \t\t\n");
      out.write("        \t  <script type=\"text/javascript\">\n");
      out.write("\t\t\tfunction SignIn(googleUser) {\n");
      out.write("\t\t\t  var profile = googleUser.getBasicProfile();\n");
      out.write("\t\t\t  console.log('reached here atleast');\n");
      out.write("\t\t\tdocument.getElementById('id').value = profile.getId();\n");
      out.write("\t\t\tdocument.getElementById('name').value = profile.getName();\n");
      out.write("\t\t\tdocument.getElementById('email').value = profile.getEmail();\n");
      out.write("\t\t\tdocument.getElementById('imageurl').value = profile.getImageUrl();\n");
      out.write("\t\t\tconsole.log('Reached till the end');\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("\t\t\t var auth2 = gapi.auth2.getAuthInstance();\n");
      out.write("\t\t\t    auth2.signOut().then(function () {\n");
      out.write("\t\t\t      console.log('User signed out.');\n");
      out.write("\t\t\t    });\n");
      out.write("\t\t\t    document.getElementById('temp_form').submit();\n");
      out.write("\t\t}\n");
      out.write("\t</script>\t\n");
      out.write("        \n");
      out.write("         \n");
      out.write("\t\t\t<form name=\"temp_form\" method=\"POST\" id = 'temp_form' action = \"doWithGmail.do\">\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"id\" id=\"id\" />\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"name\" id=\"name\" />\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"email\" id=\"email\" />\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"imageurl\" id=\"imageurl\" />\n");
      out.write("\t\t\t  <input type=\"button\" name=\"Submit\" onclick=\"submit()\" />\n");
      out.write("\t\t\t</form>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <section class=\"module\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-5 col-sm-offset-1 mb-sm-40\">\n");
      out.write("                <h4 class=\"font-alt\">Login</h4>\n");
      out.write("                <hr class=\"divider-w mb-10\">\n");
      out.write("                <form class=\"form\">\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"username\" type=\"text\" name=\"username\" placeholder=\"Username\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"password\" type=\"password\" name=\"password\" placeholder=\"Password\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"g-signin2\" data-onsuccess=\"SignIn\" style=\"width:200%\">\n");
      out.write("                  Test\n");
      out.write("                  </div>\n");
      out.write("                  <br>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <button class=\"btn btn-round btn-b\">Login</button>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group\"><a href=\"\"> </a></div>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-5\">\n");
      out.write("                <h4 class=\"font-alt\">Register</h4>\n");
      out.write("                <hr class=\"divider-w mb-10\">\n");
      out.write("                <form class=\"form\">\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"E-mail\" type=\"text\" name=\"email\" placeholder=\"Email\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"username\" type=\"text\" name=\"username\" placeholder=\"Username\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"password\" type=\"password\" name=\"password\" placeholder=\"Password\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <input class=\"form-control\" id=\"re-password\" type=\"password\" name=\"re-password\" placeholder=\"Re-enter Password\"/>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"g-signin2\" data-onsuccess=\"SignIn\" style=\"width:200%\">\n");
      out.write("                  </div><br>\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                    <button class=\"btn btn-block btn-round btn-b\">Register</button>\n");
      out.write("                  </div>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <div class=\"module-small bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">About Titan</h5>\n");
      out.write("                  <p>The languages only differ in their grammar, their pronunciation and their most common words.</p>\n");
      out.write("                  <p>Phone: +1 234 567 89 10</p>Fax: +1 234 567 89 10\n");
      out.write("                  <p>Email:<a href=\"#\">somecompany@example.com</a></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Recent Comments</h5>\n");
      out.write("                  <ul class=\"icon-list\">\n");
      out.write("                    <li>Maria on <a href=\"#\">Designer Desk Essentials</a></li>\n");
      out.write("                    <li>John on <a href=\"#\">Realistic Business Card Mockup</a></li>\n");
      out.write("                    <li>Andy on <a href=\"#\">Eco bag Mockup</a></li>\n");
      out.write("                    <li>Jack on <a href=\"#\">Bottle Mockup</a></li>\n");
      out.write("                    <li>Mark on <a href=\"#\">Our trip to the Alps</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Blog Categories</h5>\n");
      out.write("                  <ul class=\"icon-list\">\n");
      out.write("                    <li><a href=\"#\">Photography - 7</a></li>\n");
      out.write("                    <li><a href=\"#\">Web Design - 3</a></li>\n");
      out.write("                    <li><a href=\"#\">Illustration - 12</a></li>\n");
      out.write("                    <li><a href=\"#\">Marketing - 1</a></li>\n");
      out.write("                    <li><a href=\"#\">Wordpress - 16</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Popular Posts</h5>\n");
      out.write("                  <ul class=\"widget-posts\">\n");
      out.write("                    <li class=\"clearfix\">\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-1.jpg\" alt=\"Post Thumbnail\"/></a></div>\n");
      out.write("                      <div class=\"widget-posts-body\">\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Designer Desk Essentials</a></div>\n");
      out.write("                        <div class=\"widget-posts-meta\">23 january</div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"clearfix\">\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-2.jpg\" alt=\"Post Thumbnail\"/></a></div>\n");
      out.write("                      <div class=\"widget-posts-body\">\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Realistic Business Card Mockup</a></div>\n");
      out.write("                        <div class=\"widget-posts-meta\">15 February</div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <hr class=\"divider-d\">\n");
      out.write("        <footer class=\"footer bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6\">\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2017&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-6\">\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\n");
      out.write("    </main>\n");
      out.write("    <!--  \n");
      out.write("    JavaScripts\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
