/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-06-01 07:55:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import sethi.vishal.MyWebApp.entity.User;
import java.util.Iterator;
import sethi.vishal.MyWebApp.entity.Product;
import java.util.List;
import sethi.vishal.MyWebApp.entity.*;
import java.util.List;
import sethi.vishal.MyWebApp.classes.*;
import java.util.ArrayList;
import sethi.vishal.MyWebApp.entity.User;
import java.util.Iterator;
import sethi.vishal.MyWebApp.entity.Product;
import java.util.List;
import sethi.vishal.MyWebApp.entity.*;
import java.util.List;
import sethi.vishal.MyWebApp.classes.*;

public final class shop_005fsingle_005fproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Navigation.jsp", Long.valueOf(1496303350395L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.entity");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.classes");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.User");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!--  \n");
      out.write("    Document Title\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <title>MobiWorld</title>\n");
      out.write("    <!--  \n");
      out.write("    Favicons\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("    <!--  \n");
      out.write("    Stylesheets\n");
      out.write("    =============================================\n");
      out.write("    \n");
      out.write("    -->\n");
      out.write("    <!-- Default stylesheets-->\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Template specific stylesheets-->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Main stylesheet and color file-->\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write(" \t \n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\n");
      out.write("    <main>\n");
      out.write("      <div class=\"page-loader\">\n");
      out.write("        <div class=\"loader\">Loading...</div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>MobiWorld</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("      \r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"Index\">MobiWorld</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Chargers</a>\r\n");
      out.write(" \t\t\t\t\t<!-- Here Number of Dropdowns are removed -->\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Earphones</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Datacable</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">ScreenGaurd</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Contact Us</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("               \r\n");
      out.write("              <!--li.dropdown.navbar-cart-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\r\n");
      out.write("              <!--        span.icon-basket-->\r\n");
      out.write("              <!--        |-->\r\n");
      out.write("              <!--        span.cart-item-number 2-->\r\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                .cart-sub-totle-->\r\n");
      out.write("              <!--                    strong Total: $476.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\r\n");
      out.write("              <!--li.dropdown-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\r\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .dropdown-search-->\r\n");
      out.write("              <!--                form(role='form')-->\r\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\r\n");
      out.write("              <!--                        i.fa.fa-search-->\r\n");
      out.write("              ");

              	List<String> titles = new ArrayList<String>();
              	List<String> hrefs = new ArrayList<String>();
              	String log;
              	if(session.getAttribute("user")!=null){
              		User user = (User)session.getAttribute("user");
              		titles.add(0, "Your Orders");
              		titles.add(1, "Your Account");
              		titles.add(2, "Your Addresses");
              		titles.add(3, "Your Cart");
              		titles.add(4, "Signout");
              		hrefs.add(0,"#");
              		hrefs.add(1, "#");
              		hrefs.add(2,"#");
              		hrefs.add(3,"#");
              		hrefs.add(4,"Signout");
              		log = "Hello, "+user.getEmail();
					
              	}else{
              		titles.add(0, "SignIn");
              		titles.add(1, "Register");
              		hrefs.add(0, "Login.do");
              		hrefs.add(1, "Login.do");
              		log = "Hello, "+"Sign in";
              	}
              
              	int len = titles.size();
              
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"Login.do\" data-toggle=\"dropdown\">");
      out.print(log );
      out.write("</a>\r\n");
      out.write("                   <ul class=\"dropdown-menu\">\r\n");
      out.write("                  ");
 for(int i=0;i<len;i++){ 
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  <li><a href=\"");
      out.print( hrefs.get(i));
      out.write('"');
      out.write('>');
      out.print(titles.get(i) );
      out.write("</a></li>\r\n");
      out.write("                  \r\n");
      out.write("                  ");
} 
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>");
      out.write("\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      ");

      	ProductDisplay product = (ProductDisplay)session.getAttribute("product");
      	List<String> images = product.getImages();
      	System.out.println(images.size());
      	String first = (images.size()==0)?"":images.get(0) ;
      	List<Review> reviews = product.getReviews();
      	int avg = 0;
      	
      	if(reviews.size()>0){
      		for(Review review: reviews){
          		avg+=review.getRating();
          	}
      		avg = avg/reviews.size();
      	}
      	
      	
      	
      	
      	
      
      out.write("\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("      <div class=\"main\">\n");
      out.write("        <section class=\"module\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 mb-sm-40\"><a class=\"gallery\" href=\"assets/images/shop/");
      out.print( first);
      out.write("\"><img src=\"assets/images/shop/");
      out.print(first );
      out.write("\" alt=\"Single Product Image\"/></a>\n");
      out.write("                <ul class=\"product-gallery\">\n");
      out.write("                  ");
 for(int i=1, j=images.size();i<j;i++){ 
      out.write("\n");
      out.write("                  <li><a class=\"gallery\" href=\"assets/images/shop/");
      out.print( images.get(i));
      out.write("\"></a><img src=\"assets/images/shop/");
      out.print(images.get(i)  );
      out.write("\" alt=\"Single Product\"/></li>\n");
      out.write("                   ");
} 
      out.write("\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-6\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <h1 class=\"product-title font-alt\">");
      out.print(product.getName() );
      out.write("</h1>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-20\">\n");
      out.write("                  <div class=\"col-sm-12\">");
for(int i=1;i<=avg;i++) { 
      out.write(" <span><i class=\"fa fa-star star\"></i></span> ");
 } 
      out.write("    ");
 for(int i=avg;i<5;i++){ 
      out.write("   <span><i class=\"fa fa-star star-off\"></i></span> ");
} 
      out.write("<a class=\"open-tab section-scroll\" href=\"#reviews\">-");
      out.print( reviews.size() );
      out.write("customer reviews</a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-20\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                  ");
 String price = (product.getAvail()==1)?"Rs."+product.getPrice()+"":"Out Of Stock"; 
      out.write("\n");
      out.write("                    <div class=\"price font-alt\"><span class=\"amount\">");
      out.print(price );
      out.write("</span></div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-20\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"description\">\n");
      out.write("                      <p>");
      out.print(product.getDescription() );
      out.write("</p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-20\">\n");
      out.write("                  <div class=\"col-sm-4 mb-sm-20\">\n");
      out.write("                  <script type=\"text/javascript\" >\n");
      out.write("\t      \t\t\tfunction addTo(temp)\n");
      out.write("\t  \t\t\t\t{\t\n");
      out.write("\t  \t\t\t\t\t \n");
      out.write("\t      \t\t\t\ttemp.submit();\n");
      out.write("\t      \t\t\t\treturn false;\t\n");
      out.write("\t  \t\t\t\t}\t\n");
      out.write("\n");
      out.write("  \t\t\t\t</script>\n");
      out.write("                   \n");
      out.write("                  \t<form method = \"POST\" action = \"AddToCart\" id = \"cartform\">\n");
      out.write("                    \t<input class=\"form-control input-lg\" type=\"number\" name=\"count\" value=\"1\" max=\"40\" min=\"1\" required=\"required\"/>\n");
      out.write("                  \t\t<input type = \"hidden\" name = \"prodid\" value = \"");
      out.print( product.getId() );
      out.write("\"/>\n");
      out.write("                   \t</form>\n");
      out.write("                  </div>\n");
      out.write("                  \t\n");
      out.write("                  <div class=\"col-sm-8\"><button onclick=\"addTo(document.getElementById('cartform'))\" class=\"btn btn-lg btn-block btn-round btn-b\" >Add To Cart</button></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row mb-20\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"product_meta\">Categories:<a href=\"#\">");
      out.print(product.getType() );
      out.write("</a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row mt-70\">\n");
      out.write("              <div class=\"col-sm-12\">\n");
      out.write("                <ul class=\"nav nav-tabs font-alt\" role=\"tablist\">\n");
      out.write("                  <li class=\"active\"><a href=\"#description\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Description</a></li>\n");
      out.write("                  <li><a href=\"#data-sheet\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Data sheet</a></li>\n");
      out.write("                  <li><a href=\"#reviews\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Reviews (");
      out.print(reviews.size() );
      out.write(")</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"tab-content\">\n");
      out.write("                  <div class=\"tab-pane active\" id=\"description\">\n");
      out.write("                    <p>");
      out.print(product.getDescription() );
      out.write("</p>\n");
      out.write("                     \n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"tab-pane\" id=\"data-sheet\">\n");
      out.write("                    <table class=\"table table-striped ds-table table-responsive\">\n");
      out.write("                      <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                          <th>Title</th>\n");
      out.write("                          <th>");
      out.print(product.getName() );
      out.write("</th>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td>Type</td>\n");
      out.write("                          <td>");
      out.print(product.getType() );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td>Price</td>\n");
      out.write("                          <td>");
      out.print(product.getPrice() );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                        \t");
  
      out.write("\n");
      out.write("                          <td>Available Colors</td>\n");
      out.write("                          <td>");
      out.print(product.getColors().toString() );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td>Brand</td>\n");
      out.write("                          <td>");
      out.print(product.getBrand() );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("                      </tbody>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"tab-pane\" id=\"reviews\">\n");
      out.write("                    <div class=\"comments reviews\">\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    ");
for(Review review: reviews){ 
      out.write("\n");
      out.write("                    \n");
      out.write("                      <div class=\"comment clearfix\">\n");
      out.write("                        <div class=\"comment-avatar\"><img src=\"\" alt=\"avatar\"/></div>\n");
      out.write("                        <div class=\"comment-content clearfix\">\n");
      out.write("                          <div class=\"comment-author font-alt\"><a href=\"#\">");
      out.print(review.getName() );
      out.write("</a></div>\n");
      out.write("                          <div class=\"comment-body\">\n");
      out.write("                            <p>");
      out.print(review.getReview() );
      out.write("</p>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"comment-meta font-alt\">");
      out.print(review.getDate() );
      out.write('-');
for(int i=1;i<=review.getRating();i++) { 
      out.write(" <span><i class=\"fa fa-star star\"></i></span> ");
 } 
      out.write("    ");
 for(int i=review.getRating();i<5;i++){ 
      out.write("   <span><i class=\"fa fa-star star-off\"></i></span> ");
} 
      out.write("\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                       \n");
      out.write("                      \n");
      out.write("                      ");
 } 
      out.write("\n");
      out.write("                      \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    <div class=\"comment-form mt-30\">\n");
      out.write("                      <h4 class=\"comment-form-title font-alt\">Add review</h4>\n");
      out.write("                      <form method=\"post\" action = \"addReview?no=");
      out.print( product.getNo() );
      out.write("\">>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                          <div class=\"col-sm-4\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                              <label class=\"sr-only\" for=\"name\"  >Name</label>\n");
      out.write("                              <input class=\"form-control\" id=\"name\" type=\"text\" name=\"name\" placeholder=\"Name\" required/>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"col-sm-4\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                              <label class=\"sr-only\" for=\"email\" >Email</label>\n");
      out.write("                              <input class=\"form-control\" id=\"email\" type=\"text\" name=\"email\" placeholder=\"E-mail\" required/>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"col-sm-4\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                              <select class=\"form-control\" name = \"rating\" required>\n");
      out.write("                                <option selected=\"true\" disabled=\"\"  >Rating</option>\n");
      out.write("                                <option value=\"1\">1</option>\n");
      out.write("                                <option value=\"2\">2</option>\n");
      out.write("                                <option value=\"3\">3</option>\n");
      out.write("                                <option value=\"4\">4</option>\n");
      out.write("                                <option value=\"5\">5</option>\n");
      out.write("                              </select>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"col-sm-12\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                              <textarea class=\"form-control\" id=\"\" name=\"review\" rows=\"4\" placeholder=\"Review\" required></textarea>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"col-sm-12\">\n");
      out.write("                            <button class=\"btn btn-round btn-d\" type=\"submit\">Submit Review</button>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </form>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        ");

        	//Related Products Section
        	List<RelatedProduct> related = (List<RelatedProduct>)session.getAttribute("related");
        	
        
        
      out.write("\n");
      out.write("        \n");
      out.write("        <hr class=\"divider-w\">\n");
      out.write("        <section class=\"module-small\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\n");
      out.write("                <h2 class=\"module-title font-alt\">Related Products</h2>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row multi-columns-row\">\n");
      out.write("            \n");
      out.write("            ");
 for(RelatedProduct relPro: related){ 
            	String href = "showSingle?id="+relPro.getId();
            	String price2 = (relPro.getAvail()==0)?("OUT OF STOCK"):("Rs "+relPro.getPrice());
            
            
      out.write("\n");
      out.write("            \n");
      out.write("            \n");
      out.write("              <div class=\"col-sm-6 col-md-3 col-lg-3\">\n");
      out.write("                <div class=\"shop-item\">\n");
      out.write("                  <div class=\"shop-item-image\"><img src=\"assets/images/shop/");
      out.print(relPro.getImage() );
      out.write("\" alt=\"");
      out.print( relPro.getName() );
      out.write("\"/>\n");
      out.write("                    <div class=\"shop-item-detail\"><a class=\"btn btn-round btn-b\"><span class=\"icon-basket\">Add To Cart</span></a></div>\n");
      out.write("                  </div>\n");
      out.write("                  <h4 class=\"shop-item-title font-alt\"><a href=\"");
      out.print( href );
      out.write('"');
      out.write('>');
      out.print( relPro.getName() );
      out.write("</a></h4>");
      out.print(price2);
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("               \n");
      out.write("              \n");
      out.write("              \n");
      out.write("             ");
 } 
      out.write(" \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <hr class=\"divider-w\">\n");
      out.write("        <section class=\"module\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\n");
      out.write("                <h2 class=\"module-title font-alt\">Exclusive products</h2>\n");
      out.write("                <div class=\"module-subtitle font-serif\">The languages only differ in their grammar, their pronunciation and their most common words.</div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"owl-carousel text-center\" data-items=\"5\" data-pagination=\"false\" data-navigation=\"false\">\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-1.jpg\" alt=\"Leather belt\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£12.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-3.jpg\" alt=\"Derby shoes\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Derby shoes</a></h4>Â£54.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-2.jpg\" alt=\"Leather belt\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£19.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-4.jpg\" alt=\"Leather belt\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£14.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-5.jpg\" alt=\"Chelsea boots\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Chelsea boots</a></h4>Â£44.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-item\">\n");
      out.write("                  <div class=\"col-sm-12\">\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-6.jpg\" alt=\"Leather belt\"/></a>\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£19.00\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("        <div class=\"module-small bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">About Titan</h5>\n");
      out.write("                  <p>The languages only differ in their grammar, their pronunciation and their most common words.</p>\n");
      out.write("                  <p>Phone: +1 234 567 89 10</p>Fax: +1 234 567 89 10\n");
      out.write("                  <p>Email:<a href=\"#\">somecompany@example.com</a></p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Recent Comments</h5>\n");
      out.write("                  <ul class=\"icon-list\">\n");
      out.write("                    <li>Maria on <a href=\"#\">Designer Desk Essentials</a></li>\n");
      out.write("                    <li>John on <a href=\"#\">Realistic Business Card Mockup</a></li>\n");
      out.write("                    <li>Andy on <a href=\"#\">Eco bag Mockup</a></li>\n");
      out.write("                    <li>Jack on <a href=\"#\">Bottle Mockup</a></li>\n");
      out.write("                    <li>Mark on <a href=\"#\">Our trip to the Alps</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Blog Categories</h5>\n");
      out.write("                  <ul class=\"icon-list\">\n");
      out.write("                    <li><a href=\"#\">Photography - 7</a></li>\n");
      out.write("                    <li><a href=\"#\">Web Design - 3</a></li>\n");
      out.write("                    <li><a href=\"#\">Illustration - 12</a></li>\n");
      out.write("                    <li><a href=\"#\">Marketing - 1</a></li>\n");
      out.write("                    <li><a href=\"#\">Wordpress - 16</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-3\">\n");
      out.write("                <div class=\"widget\">\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Popular Posts</h5>\n");
      out.write("                  <ul class=\"widget-posts\">\n");
      out.write("                    <li class=\"clearfix\">\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-1.jpg\" alt=\"Post Thumbnail\"/></a></div>\n");
      out.write("                      <div class=\"widget-posts-body\">\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Designer Desk Essentials</a></div>\n");
      out.write("                        <div class=\"widget-posts-meta\">23 january</div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"clearfix\">\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-2.jpg\" alt=\"Post Thumbnail\"/></a></div>\n");
      out.write("                      <div class=\"widget-posts-body\">\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Realistic Business Card Mockup</a></div>\n");
      out.write("                        <div class=\"widget-posts-meta\">15 February</div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <hr class=\"divider-d\">\n");
      out.write("        <footer class=\"footer bg-dark\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-6\">\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2017&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-6\">\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </footer>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\n");
      out.write("    </main>\n");
      out.write("    <!--  \n");
      out.write("    JavaScripts\n");
      out.write("    =============================================\n");
      out.write("    -->\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
