/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-06-11 16:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet'>\r\n");
      out.write("<link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel='stylesheet'>\r\n");
      out.write("<style>\r\n");
      out.write("body{font-family: 'Ropa Sans', sans-serif; color:#666; font-size:14px; color:#333}\r\n");
      out.write("li,ul,body,input{margin:0; padding:0; list-style:none}\r\n");
      out.write("#login-form{width:350px; background:#FFF; margin:0 auto; margin-top:70px; background:#f8f8f8; overflow:hidden; border-radius:7px}\r\n");
      out.write(".form-header{display:table; clear:both}\r\n");
      out.write(".form-header label{display:block; cursor:pointer; z-index:999}\r\n");
      out.write(".form-header li{margin:0; line-height:60px; width:175px; text-align:center; background:#eee; font-size:18px; float:left; transition:all 600ms ease}\r\n");
      out.write("\r\n");
      out.write("/*sectiop*/\r\n");
      out.write(".section-out{width:700px; float:left; transition:all 600ms ease}\r\n");
      out.write(".section-out:after{content:''; clear:both; display:table}\r\n");
      out.write(".section-out section{width:350px; float:left}\r\n");
      out.write("\r\n");
      out.write(".login{padding:20px}\r\n");
      out.write(".ul-list{clear:both; display:table; width:100%}\r\n");
      out.write(".ul-list:after{content:''; clear:both; display:table}\r\n");
      out.write(".ul-list li{ margin:0 auto; margin-bottom:12px}\r\n");
      out.write(".input{background:#fff; transition:all 800ms; width:247px; border-radius:3px 0 0 3px; font-family: 'Ropa Sans', sans-serif; border:solid 1px #ccc; border-right:none; outline:none; color:#999; height:40px; line-height:40px; display:inline-block; padding-left:10px; font-size:16px}\r\n");
      out.write(".input,.login span.icon{vertical-align:top}\r\n");
      out.write(".login span.icon{width:50px; transition:all 800ms; text-align:center; color:#999; height:40px; border-radius:0 3px 3px 0; background:#e8e8e8; height:40px; line-height:40px; display:inline-block; border:solid 1px #ccc; border-left:none; font-size:16px}\r\n");
      out.write(".input:focus:invalid{border-color:red}\r\n");
      out.write(".input:focus:invalid+.icon{border-color:red}\r\n");
      out.write(".input:focus:valid{border-color:green}\r\n");
      out.write(".input:focus:valid+.icon{border-color:green}\r\n");
      out.write("#check,#check1{top:1px; position:relative}\r\n");
      out.write(".btn{border:none; outline:none; background:#0099CC; border-bottom:solid 4px #006699; font-family: 'Ropa Sans', sans-serif; margin:0 auto; display:block; height:40px; width:100%; padding:0 10px; border-radius:3px; font-size:16px; color:#FFF}\r\n");
      out.write("\r\n");
      out.write(".social-login{padding:15px 20px; background:#f1f1f1; border-top:solid 2px #e8e8e8; text-align:right}\r\n");
      out.write(".social-login a{display:inline-block; height:35px; text-align:center; line-height:35px; width:35px; margin:0 3px; text-decoration:none; color:#FFFFFF}\r\n");
      out.write(".form a i.fa{line-height:35px}\r\n");
      out.write(".fb{background:#305891} .tw{background:#2ca8d2} .gp{background:#ce4d39} .in{background:#006699}\r\n");
      out.write(".remember{width:50%; display:inline-block; clear:both; font-size:14px}\r\n");
      out.write(".remember:nth-child(2){text-align:right}\r\n");
      out.write(".remember a{text-decoration:none; color:#666}\r\n");
      out.write("\r\n");
      out.write(".hide{display:none}\r\n");
      out.write("\r\n");
      out.write("/*swich form*/\r\n");
      out.write("#signup:checked~.section-out{margin-left:-350px}\r\n");
      out.write("#login:checked~.section-out{margin-left:0px}\r\n");
      out.write("#login:checked~div .form-header li:nth-child(1),#signup:checked~div .form-header li:nth-child(2){background:#e8e8e8}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"login-form\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"radio\" checked id=\"login\" name=\"switch\" class=\"hide\">\r\n");
      out.write("<input type=\"radio\" id=\"signup\" name=\"switch\" class=\"hide\">\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<ul class=\"form-header\">\r\n");
      out.write("<li><label for=\"login\"><i class=\"fa fa-lock\"></i> LOGIN<label for=\"login\"></li>\r\n");
      out.write("<li><label for=\"signup\"><i class=\"fa fa-credit-card\"></i> REGISTER</label></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"section-out\">\r\n");
      out.write("<section class=\"login-section\">\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<ul class=\"ul-list\">\r\n");
      out.write("<li><input type=\"email\" required class=\"input\" placeholder=\"Your Email\"/><span class=\"icon\"><i class=\"fa fa-user\"></i></span></li>\r\n");
      out.write("<li><input type=\"password\" required class=\"input\" placeholder=\"Password\"/><span class=\"icon\"><i class=\"fa fa-lock\"></i></span></li>\r\n");
      out.write("<li><span class=\"remember\"><input type=\"checkbox\" id=\"check\"> <label for=\"check\">Remember Me</label></span><span class=\"remember\"><a href=\"\">Forget Password</a></span></li>\r\n");
      out.write("<li><input type=\"submit\" value=\"SIGN IN\" class=\"btn\"></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"social-login\">Or sign in with &nbsp;\r\n");
      out.write("<a href=\"\" class=\"fb\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"tw\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"gp\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"in\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"signup-section\">\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<ul class=\"ul-list\">\r\n");
      out.write("<li><input type=\"email\" required class=\"input\" placeholder=\"Your Email\"/><span class=\"icon\"><i class=\"fa fa-user\"></i></span></li>\r\n");
      out.write("<li><input type=\"password\" required class=\"input\" placeholder=\"Password\"/><span class=\"icon\"><i class=\"fa fa-lock\"></i></span></li>\r\n");
      out.write("<li><input type=\"checkbox\" id=\"check1\"> <label for=\"check1\">I accept terms and conditions</label></li>\r\n");
      out.write("<li><input type=\"submit\" value=\"SIGN UP\" class=\"btn\"></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"social-login\">Or sign up with &nbsp;\r\n");
      out.write("<a href=\"\" class=\"fb\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"tw\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"gp\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"in\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
