/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-06-20 21:37:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import sethi.vishal.MyWebApp.entity.User;
import java.util.Iterator;
import sethi.vishal.MyWebApp.entity.Product;
import java.util.List;
import sethi.vishal.MyWebApp.entity.*;
import java.util.List;
import sethi.vishal.MyWebApp.classes.*;
import java.util.ArrayList;
import sethi.vishal.MyWebApp.entity.User;
import java.util.Iterator;
import sethi.vishal.MyWebApp.entity.Product;
import java.util.List;
import sethi.vishal.MyWebApp.entity.*;
import java.util.List;
import sethi.vishal.MyWebApp.classes.*;

public final class shop_005fsingle_005fproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/LoginForm.jsp", Long.valueOf(1497441447068L));
    _jspx_dependants.put("/Navigation.jsp", Long.valueOf(1497440830738L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.entity");
    _jspx_imports_packages.add("sethi.vishal.MyWebApp.classes");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.User");
    _jspx_imports_classes.add("sethi.vishal.MyWebApp.entity.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>MobiWorld</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("        <link href=\"assets/css/model.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t      var xml;\r\n");
      out.write("\t      var text;\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\txml = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\tconsole.log(\"check\");\r\n");
      out.write("\t\t\t}else if(window.ActiveXObject){\r\n");
      out.write("\t\t\t\txml = new ActiveXObject(\"MICROSOFT.XMLHttp\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction sendMessageToCartServer(id, name){\r\n");
      out.write("\t\t\t\ttext = name;\r\n");
      out.write("\t\t\t\txml.open(\"POST\", \"AddToCart?count=1&prodid=\"+id,true);\r\n");
      out.write("\t\t\t\txml.onreadystatechange = receiveMessageFromCartServer;\r\n");
      out.write("\t\t\t\txml.send();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction receiveMessageFromCartServer(){\r\n");
      out.write("\t\t\t\tif(xml.readyState==4&&xml.status==200){\r\n");
      out.write("\t\t\t\t\tvar modal = document.getElementById('AddedToCart');\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('item_header').innerHTML = text+\", has been added to your cart\";\r\n");
      out.write("\t\t\t\t\tmodal.style.display = 'block';\r\n");
      out.write("\t\t\t\t\twindow.onclick = function(event) {\r\n");
      out.write("\t\t\t\t\t    if (event.target == modal) {\r\n");
      out.write("\t\t\t\t\t        modal.style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar span = document.getElementById(\"spanAddedToCart\");\r\n");
      out.write("\t\t\t\t\tspan.onclick = function(event){\r\n");
      out.write("\t\t\t\t\t\tconsole.log('entered');\r\n");
      out.write("\t\t\t\t\t\tif(event.target==span){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log('targated');\r\n");
      out.write("\t\t\t\t\t\t\tmodal.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction doWhatYouWant(){\r\n");
      out.write("\t\t\t\tjQuery('#divForCart').load(' #divForCart');\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t// When the user clicks on div, open the popup\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tfunction openLogin(){\r\n");
      out.write("\t\t\t\tvar modal = document.getElementById('login_form');\r\n");
      out.write("\t\t\t\tmodal.style.display = \"block\";\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\twindow.onclick = function(event) {\r\n");
      out.write("\t\t\t\t    if (event.target == modal) {\r\n");
      out.write("\t\t\t\t        modal.style.display = \"none\";\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("      </script>\r\n");
      out.write(" \t \r\n");
      out.write(" \r\n");
      out.write(" \t \r\n");
      out.write(" \t \r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div id=\"AddedToCart\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span id=spanAddedToCart class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Item Added To Cart</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <h3 id=\"item_header\"></h3>\r\n");
      out.write("      <p id =\"item_desc\"></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("       <div class=\"herelog\"><a href = \"DisplayCart\"><button onclick=\"Login.do; return false;\" class=\"btn btn-border-w btn-circle\" type=submit>Check Your Cart</button></a></div>\r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- The Modal -->\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <div class=\"modal-header\">\r\n");
      out.write("      <span class=\"close\">&times;</span>\r\n");
      out.write("      <h2>Login Required </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-body\">\r\n");
      out.write("      <h3>You have to login to add it to your cart</h3>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"modal-footer\">\r\n");
      out.write("       <div class=\"herelog\"><a href = \"#\"><button onclick=\"openLogin(); return false;\" class=\"btn btn-border-w btn-circle\" type=submit>Login</button></a></div>\r\n");
      out.write("    \t<div class=\"herereg\"><a href=\"Login.do\"><button onclick=\"openLogin(); return false;\" class=\"btn btn-border-w btn-circle\" type=submit>Register</button></a></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("      <div class=\"page-loader\">\r\n");
      out.write("        <div class=\"loader\">Loading...</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>MobiWorld</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"assets/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    \r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link href=\"assets/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"assets/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"assets/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <style rel=\"stylesheet\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t#searchInput{\r\n");
      out.write("    \t\tborder-radius: 25px;\r\n");
      out.write("\t\t    float:right; \r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t     \r\n");
      out.write("    \t}\r\n");
      out.write("    \t.Mydropbtn {\r\n");
      out.write("\t\t    background-color: white;\r\n");
      out.write("\t\t    color: white;\r\n");
      out.write("\t\t    padding: 8px;\r\n");
      out.write("\t\t    font-size: 16px;\r\n");
      out.write("\t\t    border: none;\r\n");
      out.write("\t\t    cursor: pointer;\r\n");
      out.write("\t\t    margin-bottom: 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    margin-top:55px;\r\n");
      out.write("    margin-left:10px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown-content a:hover {background-color: #f1f1f1}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown:hover .Mydropdown-content {\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Mydropdown:hover .Mydropbtn {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar xml;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txml = new XMLHttpRequest();\r\n");
      out.write("\t\tconsole.log('got');\r\n");
      out.write("\t}else if(window.ActiveXObject){\r\n");
      out.write("\t\txml = new ActiveXObject(\"MICROSOFT.XMLHttp\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction showList(){\r\n");
      out.write("\t\tvar text = document.getElementById('searchInput').value;\r\n");
      out.write("\t\tconsole.log(text);\r\n");
      out.write("\t\txml.open(\"POST\", 'SearchProducts?text='+text, true);\r\n");
      out.write("\t\txml.onreadystatechange = displayList;\r\n");
      out.write("\t\txml.send();\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction displayList(){\r\n");
      out.write("\t\tif(xml.readyState==4&&xml.status==200){\r\n");
      out.write("\t\t\tconsole.log('got state');\r\n");
      out.write("\t\t\tvar drop = document.getElementById(\"searchDropDown\");\r\n");
      out.write("\t\t\tconsole.log('got drop down');\r\n");
      out.write("\t\t\t");
 
				List<Product> searchBoxProducts = (List<Product>)session.getAttribute("searchBoxProducts");
				if(searchBoxProducts!=null)	
				for(Product product:searchBoxProducts){
			
      out.write("\r\n");
      out.write("\t\t\t\tvar a = document.createElement(\"a\");\r\n");
      out.write("\t\t\t\ta.href = \"showSingle?id=");
      out.print( product.getId());
      out.write("\";\r\n");
      out.write("\t\t\t\ta.innerHTML = '");
      out.print(product.getName() );
      out.write("';\r\n");
      out.write("\t\t\t\tdrop.appendChild(a);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction openDropDown(){\r\n");
      out.write("\t\tvar drop = document.getElementById('Mydropdown');\r\n");
      out.write("\t\tvar content = document.getElementById('Mydropdown-content');\r\n");
      out.write("\t\tdrop.style.display = 'block';\r\n");
      out.write("\t\tcontent.style.display = 'block';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction closeDropDown(){\r\n");
      out.write("\t\tvar drop =  document.getElementById('Mydropdown');\r\n");
      out.write("\t\tvar content = document.getElementById('Mydropdown-content');\r\n");
      out.write("\t\tdrop.style.display = 'none';\r\n");
      out.write("\t\tcontent.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("    <main>\r\n");
      out.write("       \r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\" id=\"navBar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"Index\">MobiWorld</a>\r\n");
      out.write("          \t <div  class=\"Mydropdown\" onfocus=\"openDropDown()\" onblur=\"closeDropDown()\">\r\n");
      out.write("          \t <input class=\"Mydropbtn\" id=\"searchInput\" onfocus=\"showList()\" value=\"charger\"   oninput=\"showList()\" style=\"float:right;margin-top: 5%;color:black\" class=\"navbar-header\" type=\"text\" placeholder=\"Press Enter to search\">\r\n");
      out.write("          \t <div id=\"searchDropDown\" class=\"Mydropdown-content\">\r\n");
      out.write("          \t \t  \r\n");
      out.write("          \t \t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("          \t </div>\r\n");
      out.write("          \t \r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("          \t\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li  class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Chargers</a>\r\n");
      out.write(" \t\t\t\t\t<!-- Here Number of Dropdowns are removed -->\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Earphones</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Datacable</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">ScreenGaurd</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"Contact\" data-toggle=\"dropdown\">Contact Us</a>\r\n");
      out.write("                 \r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("               \r\n");
      out.write("              <!--li.dropdown.navbar-cart-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\r\n");
      out.write("              <!--        span.icon-basket-->\r\n");
      out.write("              <!--        |-->\r\n");
      out.write("              <!--        span.cart-item-number 2-->\r\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                .cart-sub-totle-->\r\n");
      out.write("              <!--                    strong Total: $476.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\r\n");
      out.write("              <!--li.dropdown-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\r\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .dropdown-search-->\r\n");
      out.write("              <!--                form(role='form')-->\r\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\r\n");
      out.write("              <!--                        i.fa.fa-search-->\r\n");
      out.write("              ");

              	List<String> titles = new ArrayList<String>();
              	List<String> hrefs = new ArrayList<String>();
              	String log;
              	if(session.getAttribute("user")!=null){
              		User user = (User)session.getAttribute("user");
              		titles.add(0, "Your Orders");
              		titles.add(1, "Your Account");
              		titles.add(2, "Your Addresses");
              		titles.add(3, "Your Cart");
              		titles.add(4, "Signout");
              		hrefs.add(0,"#");
              		hrefs.add(1, "#");
              		hrefs.add(2,"#");
              		hrefs.add(3,"DisplayCart");
              		hrefs.add(4,"Signout");
              		log = "Hello, "+user.getEmail();
					
              	}else{
              		titles.add(0, "SignIn");
              		titles.add(1, "Register");
              		hrefs.add(0, "#");
              		hrefs.add(1, "#");
              		
              		log = "Hello, "+"Sign in";
              	}
              
              	int len = titles.size();
              
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <li class=\"dropdown\"><a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">");
      out.print(log );
      out.write("</a>\r\n");
      out.write("                   <ul class=\"dropdown-menu\">\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                  ");
 for(int i=0;i<len;i++){ 
      out.write("\r\n");
      out.write("                  ");
 if(len==2) { 
      out.write("\r\n");
      out.write("                  \t\t<li><a href=\"");
      out.print( hrefs.get(i));
      out.write("\" onclick=\"openLogin();return false;\">");
      out.print(titles.get(i) );
      out.write("</a></li>\r\n");
      out.write("                  ");
}  
      out.write("\r\n");
      out.write("\t\t\t        ");
if(len==5) {
      out.write("\r\n");
      out.write("\t\t            <li><a href=\"");
      out.print( hrefs.get(i));
      out.write('"');
      out.write('>');
      out.print(titles.get(i) );
      out.write("</a></li>\r\n");
      out.write("\t                ");
 } 
      out.write("\r\n");
      out.write("                  ");
} 
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      ");

      	ProductDisplay product = (ProductDisplay)session.getAttribute("product");
      	List<String> images = product.getImages();
      	System.out.println(images.size());
      	String first = (images.size()==0)?"":images.get(0) ;
      	List<Review> reviews = product.getReviews();
      	int avg = 0;
      	
      	if(reviews.size()>0){
      		int size = 0;
      		for(Review review: reviews){
          		if(review.getRegister()==1){
          			avg+=review.getRating();
          			size++;
          		}
          	}
      		if(size>=1)
      			avg = avg/size;
      	}
      	
      	
      	
      	
      	
      
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   <div id=\"login_form\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal content -->\r\n");
      out.write("  <div class = \"modal-content\" style=\"width: 352px;height: 377px\">\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("       ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-IN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>\r\n");
      out.write(" <script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" <meta name=\"google-signin-client_id\" content=\"229306623946-p03t1aro8bce7611n19v5nu3vc8fosib.apps.googleusercontent.com\">\r\n");
      out.write(" \r\n");
      out.write("<title></title>\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet'>\r\n");
      out.write("<link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel='stylesheet'>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write("li,ul,body,input{margin:0; padding:0; list-style:none}\r\n");
      out.write("#login-form{width:350px; background:#FFF; margin:0 auto; margin-top:0px; background:#f8f8f8; overflow:hidden; border-radius:7px}\r\n");
      out.write(".form-header{display:table; clear:both}\r\n");
      out.write(".form-header label{display:block; cursor:pointer; z-index:999}\r\n");
      out.write(".form-header li{margin:0; line-height:60px; width:175px; text-align:center; background:#eee; font-size:18px; float:left; transition:all 600ms ease}\r\n");
      out.write("\r\n");
      out.write("/*sectiop*/\r\n");
      out.write(".section-out{width:700px; float:left; transition:all 600ms ease}\r\n");
      out.write(".section-out:after{content:''; clear:both; display:table}\r\n");
      out.write(".section-out section{width:350px; float:left}\r\n");
      out.write("\r\n");
      out.write(".login{padding:20px}\r\n");
      out.write(".ul-list{clear:both; display:table; width:100%}\r\n");
      out.write(".ul-list:after{content:''; clear:both; display:table}\r\n");
      out.write(".ul-list li{ margin:0 auto; margin-bottom:12px}\r\n");
      out.write(".input{background:#fff; transition:all 800ms; width:247px; border-radius:3px 0 0 3px; font-family: 'Ropa Sans', sans-serif; border:solid 1px #ccc; border-right:none; outline:none; color:#999; height:40px; line-height:40px; display:inline-block; padding-left:10px; font-size:16px}\r\n");
      out.write(".input,.login span.icon{vertical-align:top}\r\n");
      out.write(".login span.icon{width:50px; transition:all 800ms; text-align:center; color:#999; height:40px; border-radius:0 3px 3px 0; background:#e8e8e8; height:40px; line-height:40px; display:inline-block; border:solid 1px #ccc; border-left:none; font-size:16px}\r\n");
      out.write(".input:focus:invalid{border-color:red}\r\n");
      out.write(".input:focus:invalid+.icon{border-color:red}\r\n");
      out.write(".input:focus:valid{border-color:green}\r\n");
      out.write(".input:focus:valid+.icon{border-color:green}\r\n");
      out.write("#check,#check1{top:1px; position:relative}\r\n");
      out.write(".btn23{border:none; \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toutline:none; background:#0099CC; border-bottom:solid 4px #006699; font-family: 'Ropa Sans', sans-serif; margin:0 auto; display:block; height:40px; width:100%; padding:0 10px; border-radius:3px; font-size:16px; color:#FFF}\r\n");
      out.write("\r\n");
      out.write(".social-login{padding:15px 20px; background:#f1f1f1; border-top:solid 2px #e8e8e8; text-align:right}\r\n");
      out.write(".social-login a{display:inline-block; height:35px; text-align:center; line-height:35px; width:35px; margin:0 3px; text-decoration:none; color:#FFFFFF}\r\n");
      out.write(".form a i.fa{line-height:35px}\r\n");
      out.write(".fb{background:#305891} .tw{background:#2ca8d2} .gp{background:#ce4d39} .in{background:#006699}\r\n");
      out.write(".remember{width:50%; display:inline-block; clear:both; font-size:14px}\r\n");
      out.write(".remember:nth-child(2){text-align:right}\r\n");
      out.write(".remember a{text-decoration:none; color:#666}\r\n");
      out.write("\r\n");
      out.write(".hide{display:none}\r\n");
      out.write("\r\n");
      out.write("/*swich form*/\r\n");
      out.write("#signup:checked~.section-out{margin-left:-350px}\r\n");
      out.write("#login:checked~.section-out{margin-left:0px}\r\n");
      out.write("#login:checked~div .form-header li:nth-child(1),#signup:checked~div .form-header li:nth-child(2){background:#e8e8e8}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"login-form\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"radio\" checked id=\"login\" name=\"switch\" class=\"hide\">\r\n");
      out.write("<input type=\"radio\" id=\"signup\" name=\"switch\" class=\"hide\">\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<ul class=\"form-header\">\r\n");
      out.write("<li><label for=\"login\"><i class=\"fa fa-lock\"></i> LOGIN<label for=\"login\"></li>\r\n");
      out.write("<li><label for=\"signup\"><i class=\"fa fa-credit-card\"></i> REGISTER</label></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write(" \t\t\tvar xml;\r\n");
      out.write(" \t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\txml = new XMLHttpRequest();\r\n");
      out.write(" \t\t\t}else if(window.ActiveXObject){\r\n");
      out.write(" \t \t\t\txml = new ActiveXObject(\"MICROSOFT.XMLHttp\");\r\n");
      out.write("\r\n");
      out.write(" \t \t\t}\r\n");
      out.write("\t\t\tfunction onSignIn(googleUser) {\r\n");
      out.write("\t\t\t  var profile = googleUser.getBasicProfile();\r\n");
      out.write("\t\t\t  console.log('reached here atleast');\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\tdocument.getElementById('id').value = profile.getId();\r\n");
      out.write("\t\t\tdocument.getElementById('name').value = profile.getName();\r\n");
      out.write("\t\t\tdocument.getElementById('email').value = profile.getEmail();\r\n");
      out.write("\t\t\tdocument.getElementById('imageurl').value = profile.getImageUrl();\r\n");
      out.write("\t\t\tconsole.log('Reached till the end');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t var auth2 = gapi.auth2.getAuthInstance();\r\n");
      out.write("\t\t\t    auth2.signOut().then(function () {\r\n");
      out.write("\t\t\t      console.log('User signed out.');\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t\tsendMessageToServer(profile,profile.getId(), profile.getName(), profile.getEmail(), profile.getImageUrl());    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction sendMessageToServer(profile, id, name, email, image){\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\txml.open(\"POST\", 'doWithGmail.do?id='+id+'&name='+profile.getName()+'&email='+profile.getEmail()+'&image='+profile.getImageUrl());\r\n");
      out.write("\t\t\t\txml.onreadystatechange = changeState;\r\n");
      out.write("\t\t\t\txml.send();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tfunction changeState(){\r\n");
      out.write("\t\t\t\tif(xml.readyState==4&&xml.status==200){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('login_form').style.display = 'none';\r\n");
      out.write("\t\t\t\t\tjQuery('#navBar').load(' #navBar');\t\r\n");
      out.write("\t\t\t\t\tjQuery('#sampleProducts').load(' #sampleProducts');\r\n");
      out.write("\t\t\t\t\tdoWhatYouWant();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t       </script>\t\r\n");
      out.write("        \t \t\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("\t\t\t<form name=\"temp_form\" method=\"POST\" id = 'temp_form' action = \"doWithGmail.do\">\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"id\" id=\"id\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"name\" id=\"name\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"email\" id=\"email\" />\r\n");
      out.write("\t\t\t  <input type=\"hidden\" name=\"imageurl\" id=\"imageurl\" />\r\n");
      out.write("\t\t\t  <input type=\"button\" name=\"Submit\" onclick=\"submit()\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"section-out\">\r\n");
      out.write("<section class=\"login-section\">\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<ul class=\"ul-list\">\r\n");
      out.write("<li><input type=\"email\" required class=\"input\" placeholder=\"Your Email\"/><span class=\"icon\"><i class=\"fa fa-user\"></i></span></li>\r\n");
      out.write("<li><input type=\"password\" required class=\"input\" placeholder=\"Password\"/><span class=\"icon\"><i class=\"fa fa-lock\"></i></span></li>\r\n");
      out.write("<li><span class=\"remember\"><input type=\"checkbox\" id=\"check\"> <label for=\"check\">Remember Me</label></span><span class=\"remember\"><a href=\"\">Forget Password</a></span></li>\r\n");
      out.write("<li><input type=\"submit\" value=\"SIGN IN\" class=\"btn23\"></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"social-login\">Or sign in with &nbsp;\r\n");
      out.write("<a href=\"\" class=\"fb\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"tw\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"gp\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("<div class=\"g-signin2\" data-onsuccess=\"onSignIn\"  >\r\n");
      out.write("<a href=\"\" class=\"in\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"signup-section\">\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<ul class=\"ul-list\">\r\n");
      out.write("<li><input type=\"email\" required class=\"input\" placeholder=\"Your Email\"/><span class=\"icon\"><i class=\"fa fa-user\"></i></span></li>\r\n");
      out.write("<li><input type=\"password\" required class=\"input\" placeholder=\"Password\"/><span class=\"icon\"><i class=\"fa fa-lock\"></i></span></li>\r\n");
      out.write("<li><input type=\"checkbox\" id=\"check1\"> <label for=\"check1\">I accept terms and conditions</label></li>\r\n");
      out.write("<li><input type=\"submit\" value=\"SIGN UP\" class=\"btn23\"></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"social-login\">Or sign up with &nbsp;\r\n");
      out.write("<a href=\"\" class=\"fb\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"tw\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"gp\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("<a href=\"\" class=\"in\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("      \r\n");
      out.write("      ");
User userChecking = (User)session.getAttribute("user");
     	 boolean askToLog;
    	if(userChecking!=null){
    		askToLog = false; 
    	}else{
    		askToLog = true;
    	}
    	String methodCall;
  		if(askToLog){
  			methodCall = "openLogin()";
  		}else{
  			methodCall = "sendMessageToCartServer('"+product.getId()+"','"+product.getName()+"')";
  		}
  		
      
      
      out.write("\r\n");
      out.write("      <div class=\"main\">\r\n");
      out.write("        <section class=\"module\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6 mb-sm-40\"><a class=\"gallery\" href=\"assets/images/shop/");
      out.print( first);
      out.write("\"><img src=\"assets/images/shop/");
      out.print(first );
      out.write("\" alt=\"Single Product Image\"/></a>\r\n");
      out.write("                <ul class=\"product-gallery\">\r\n");
      out.write("                  ");
 for(int i=1, j=images.size();i<j;i++){ 
      out.write("\r\n");
      out.write("                  <li><a class=\"gallery\" href=\"assets/images/shop/");
      out.print( images.get(i));
      out.write("\"></a><img src=\"assets/images/shop/");
      out.print(images.get(i)  );
      out.write("\" alt=\"Single Product\"/></li>\r\n");
      out.write("                   ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <h1 class=\"product-title font-alt\">");
      out.print(product.getName() );
      out.write("</h1>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row mb-20\">\r\n");
      out.write("                  <div class=\"col-sm-12\">");
for(int i=1;i<=avg;i++) { 
      out.write(" <span><i class=\"fa fa-star star\"></i></span> ");
 } 
      out.write("    ");
 for(int i=avg;i<5;i++){ 
      out.write("   <span><i class=\"fa fa-star star-off\"></i></span> ");
} 
      out.write("<a class=\"open-tab section-scroll\" href=\"#reviews\">-");
      out.print( reviews.size() );
      out.write("customer reviews</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row mb-20\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                  ");
 String price = (product.getAvail()==1)?"Rs."+product.getPrice()+"":"Out Of Stock"; 
      out.write("\r\n");
      out.write("                    <div class=\"price font-alt\"><span class=\"amount\">");
      out.print(price );
      out.write("</span></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row mb-20\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"description\">\r\n");
      out.write("                      <p>");
      out.print(product.getDescription() );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row mb-20\">\r\n");
      out.write("                  <div class=\"col-sm-4 mb-sm-20\">\r\n");
      out.write("                  <script type=\"text/javascript\" >\r\n");
      out.write("\t      \t\t\tfunction addTo(temp)\r\n");
      out.write("\t  \t\t\t\t{\t\r\n");
      out.write("\t  \t\t\t\t\t \r\n");
      out.write("\t      \t\t\t\ttemp.submit();\r\n");
      out.write("\t      \t\t\t\treturn false;\t\r\n");
      out.write("\t  \t\t\t\t}\t\r\n");
      out.write("\r\n");
      out.write("  \t\t\t\t</script>\r\n");
      out.write("                   \r\n");
      out.write("                  \t<form method = \"POST\" action = \"AddToCart\" id = \"cartform\">\r\n");
      out.write("                    \t<input class=\"form-control input-lg\" type=\"number\" id = \"count\" name=\"count\" value=\"1\" max=\"40\" min=\"1\" required=\"required\"/>\r\n");
      out.write("                  \t\t<input type = \"hidden\" name = \"prodid\" value = \"");
      out.print( product.getId() );
      out.write("\" id=\"prod_id\"/>\r\n");
      out.write("                   \t</form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \t\r\n");
      out.write("                  <div id = \"divForCart\">\t\r\n");
      out.write("                  \t\r\n");
      out.write("                  \t\r\n");
      out.write("                  <div class=\"col-sm-8\"><button onclick=\"");
      out.print( methodCall );
      out.write("; return false;\" class=\"btn btn-lg btn-block btn-round btn-b\" >Add To Cart</button></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Just to check for the popup  -->\r\n");
      out.write("                \r\n");
      out.write("                 </div>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("                <div class=\"row mb-20\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"product_meta\">Categories:<a href=\"#\">");
      out.print(product.getType() );
      out.write("</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-70\">\r\n");
      out.write("              <div class=\"col-sm-12\">\r\n");
      out.write("                <ul class=\"nav nav-tabs font-alt\" role=\"tablist\">\r\n");
      out.write("                  <li class=\"active\"><a href=\"#description\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Description</a></li>\r\n");
      out.write("                  <li><a href=\"#data-sheet\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Data sheet</a></li>\r\n");
      out.write("                  <li><a href=\"#reviews\" data-toggle=\"tab\"><span class=\"icon-tools-2\"></span>Reviews (");
      out.print(reviews.size() );
      out.write(")</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                  <div class=\"tab-pane active\" id=\"description\">\r\n");
      out.write("                    <p>");
      out.print(product.getDescription() );
      out.write("</p>\r\n");
      out.write("                     \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"tab-pane\" id=\"data-sheet\">\r\n");
      out.write("                    <table class=\"table table-striped ds-table table-responsive\">\r\n");
      out.write("                      <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th>Title</th>\r\n");
      out.write("                          <th>");
      out.print(product.getName() );
      out.write("</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>Type</td>\r\n");
      out.write("                          <td>");
      out.print(product.getType() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>Price</td>\r\n");
      out.write("                          <td>");
      out.print(product.getPrice() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                        \t");
  
      out.write("\r\n");
      out.write("                          <td>Available Colors</td>\r\n");
      out.write("                          <td>");
      out.print(product.getColors().toString() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>Brand</td>\r\n");
      out.write("                          <td>");
      out.print(product.getBrand() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"tab-pane\" id=\"reviews\">\r\n");
      out.write("                    <div class=\"comments reviews\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    ");

                    String disable = "";
        			
        			String nameOfUser = null;
        			String emailOfUser = null;
                    if(userChecking!=null){
                    	disable = "disabled";
                    	nameOfUser = userChecking.getName();
                    	emailOfUser = userChecking.getEmail();
                    } 
                    
                    for(Review review: reviews){ 
                    	String imageUrl = (review.getRegister()==1)?"assets/added/final.png":"assets/added/guest.png";
                    	 
                    	 
                    	 
                    	 
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                      <div class=\"comment clearfix\">\r\n");
      out.write("                        <div class=\"comment-avatar\"><img src=\"");
      out.print(imageUrl );
      out.write("\" alt=\"avatar\"/></div>\r\n");
      out.write("                        <div class=\"comment-content clearfix\">\r\n");
      out.write("                          <div class=\"comment-author font-alt\"><a href=\"#\">");
      out.print(review.getName() );
      out.write("</a></div>\r\n");
      out.write("                          <div class=\"comment-body\">\r\n");
      out.write("                            <p>");
      out.print(review.getReview() );
      out.write("</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"comment-meta font-alt\">");
      out.print(review.getDate() );
      out.write('-');
for(int i=1;i<=review.getRating();i++) { 
      out.write(" <span><i class=\"fa fa-star star\"></i></span> ");
 } 
      out.write("    ");
 for(int i=review.getRating();i<5;i++){ 
      out.write("   <span><i class=\"fa fa-star star-off\"></i></span> ");
} 
      out.write("\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                       \r\n");
      out.write("                      \r\n");
      out.write("                      ");
 } 
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"comment-form mt-30\">\r\n");
      out.write("                      <h4 class=\"comment-form-title font-alt\">Add review</h4>\r\n");
      out.write("                      <form method=\"post\" action = \"addReview?no=");
      out.print( product.getNo() );
      out.write("\" id = \"reviewForm\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <label class=\"sr-only\" for=\"name\"  >Name</label>\r\n");
      out.write("                              <input class=\"form-control\" id=\"name\" type=\"text\" value=\"");
      out.print( (userChecking==null)?"":nameOfUser );
      out.write('"');
      out.write(' ');
      out.write(' ');
      out.print(disable );
      out.write("  name=\"name\" placeholder=\"Name\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <label class=\"sr-only\" for=\"email\" >Email</label>\r\n");
      out.write("                              <input class=\"form-control\" value=\"");
      out.print( (userChecking==null)?"":emailOfUser );
      out.write('"');
      out.write(' ');
      out.write(' ');
      out.print(disable );
      out.write(" id=\"email\" type=\"text\" name=\"email\"  placeholder=\"E-mail\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <select class=\"form-control\" name = \"rating\" required>\r\n");
      out.write("                                <option selected=\"true\" disabled=\"\"  >Rating</option>\r\n");
      out.write("                                <option value=\"1\">1</option>\r\n");
      out.write("                                <option value=\"2\">2</option>\r\n");
      out.write("                                <option value=\"3\">3</option>\r\n");
      out.write("                                <option value=\"4\">4</option>\r\n");
      out.write("                                <option value=\"5\">5</option>\r\n");
      out.write("                              </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                              <textarea class=\"form-control\" id=\"\" name=\"review\" rows=\"4\" placeholder=\"Review\" required></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-sm-12\">\r\n");
      out.write("                            <button class=\"btn btn-round btn-d\" type=\"submit\">Submit Review</button>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        ");

        	//Related Products Section
        	List<RelatedProduct> related = (List<RelatedProduct>)session.getAttribute("related");
        	
        
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <hr class=\"divider-w\">\r\n");
      out.write("        <section class=\"module-small\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("                <h2 class=\"module-title font-alt\">Related Products</h2>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row multi-columns-row\">\r\n");
      out.write("            \r\n");
      out.write("            ");
 
           	
            
            for(RelatedProduct relPro: related){ 
            	String href = "showSingle?id="+relPro.getId();
            	String price2 = (relPro.getAvail()==0)?("OUT OF STOCK"):("Rs "+relPro.getPrice());
            
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("              <div class=\"col-sm-6 col-md-3 col-lg-3\">\r\n");
      out.write("                <div class=\"shop-item\">\r\n");
      out.write("                  <div class=\"shop-item-image\"><img src=\"assets/images/shop/");
      out.print(relPro.getImage() );
      out.write("\" alt=\"");
      out.print( relPro.getName() );
      out.write("\"/>\r\n");
      out.write("                    <div class=\"shop-item-detail\"><a class=\"btn btn-round btn-b\"><span class=\"icon-basket\">Add To Cart</span></a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <h4 class=\"shop-item-title font-alt\"><a href=\"");
      out.print( href );
      out.write('"');
      out.write('>');
      out.print( relPro.getName() );
      out.write("</a></h4>");
      out.print(price2);
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("               \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("             ");
 } 
      out.write(" \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <hr class=\"divider-w\">\r\n");
      out.write("        <section class=\"module\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("                <h2 class=\"module-title font-alt\">Exclusive products</h2>\r\n");
      out.write("                <div class=\"module-subtitle font-serif\">The languages only differ in their grammar, their pronunciation and their most common words.</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"owl-carousel text-center\" data-items=\"5\" data-pagination=\"false\" data-navigation=\"false\">\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-1.jpg\" alt=\"Leather belt\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£12.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-3.jpg\" alt=\"Derby shoes\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Derby shoes</a></h4>Â£54.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-2.jpg\" alt=\"Leather belt\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£19.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-4.jpg\" alt=\"Leather belt\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£14.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-5.jpg\" alt=\"Chelsea boots\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Chelsea boots</a></h4>Â£44.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-item\">\r\n");
      out.write("                  <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"ex-product\"><a href=\"#\"><img src=\"assets/images/shop/product-6.jpg\" alt=\"Leather belt\"/></a>\r\n");
      out.write("                      <h4 class=\"shop-item-title font-alt\"><a href=\"#\">Leather belt</a></h4>Â£19.00\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"module-small bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">About Titan</h5>\r\n");
      out.write("                  <p>The languages only differ in their grammar, their pronunciation and their most common words.</p>\r\n");
      out.write("                  <p>Phone: +1 234 567 89 10</p>Fax: +1 234 567 89 10\r\n");
      out.write("                  <p>Email:<a href=\"#\">somecompany@example.com</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Recent Comments</h5>\r\n");
      out.write("                  <ul class=\"icon-list\">\r\n");
      out.write("                    <li>Maria on <a href=\"#\">Designer Desk Essentials</a></li>\r\n");
      out.write("                    <li>John on <a href=\"#\">Realistic Business Card Mockup</a></li>\r\n");
      out.write("                    <li>Andy on <a href=\"#\">Eco bag Mockup</a></li>\r\n");
      out.write("                    <li>Jack on <a href=\"#\">Bottle Mockup</a></li>\r\n");
      out.write("                    <li>Mark on <a href=\"#\">Our trip to the Alps</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Blog Categories</h5>\r\n");
      out.write("                  <ul class=\"icon-list\">\r\n");
      out.write("                    <li><a href=\"#\">Photography - 7</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Web Design - 3</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Illustration - 12</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Marketing - 1</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Wordpress - 16</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <div class=\"widget\">\r\n");
      out.write("                  <h5 class=\"widget-title font-alt\">Popular Posts</h5>\r\n");
      out.write("                  <ul class=\"widget-posts\">\r\n");
      out.write("                    <li class=\"clearfix\">\r\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-1.jpg\" alt=\"Post Thumbnail\"/></a></div>\r\n");
      out.write("                      <div class=\"widget-posts-body\">\r\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Designer Desk Essentials</a></div>\r\n");
      out.write("                        <div class=\"widget-posts-meta\">23 january</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"clearfix\">\r\n");
      out.write("                      <div class=\"widget-posts-image\"><a href=\"#\"><img src=\"assets/images/rp-2.jpg\" alt=\"Post Thumbnail\"/></a></div>\r\n");
      out.write("                      <div class=\"widget-posts-body\">\r\n");
      out.write("                        <div class=\"widget-posts-title\"><a href=\"#\">Realistic Business Card Mockup</a></div>\r\n");
      out.write("                        <div class=\"widget-posts-meta\">15 February</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"divider-d\">\r\n");
      out.write("        <footer class=\"footer bg-dark\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <p class=\"copyright font-alt\">&copy; 2017&nbsp;<a href=\"index.html\">TitaN</a>, All Rights Reserved</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-6\">\r\n");
      out.write("                <div class=\"footer-social-links\"><a href=\"#\"><i class=\"fa fa-facebook\"></i></a><a href=\"#\"><i class=\"fa fa-twitter\"></i></a><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a><a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"scroll-up\"><a href=\"#totop\"><i class=\"fa fa-angle-double-up\"></i></a></div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!--  \r\n");
      out.write("    JavaScripts\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"assets/lib/jquery/dist/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/wow/dist/wow.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/isotope/dist/isotope.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/flexslider/jquery.flexslider.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/smoothscroll.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"assets/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
